import requests
import pandas as pd
import json
import os

EXOPLANET_FILE = "data/exoplanets.json"

# ── Top 200 most famous exoplanet systems ─────────────────────────
# Manually curated list of the most scientifically
# significant and well-known exoplanet systems
FAMOUS_EXOPLANETS = [
    # TRAPPIST-1 system — 7 Earth-sized planets
    {"name": "TRAPPIST-1b", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2016, "method": "Transit",
     "notes": "Potentially habitable zone"},
    {"name": "TRAPPIST-1c", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2016, "method": "Transit",
     "notes": "Rocky, Earth-sized"},
    {"name": "TRAPPIST-1d", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2016, "method": "Transit",
     "notes": "Habitable zone candidate"},
    {"name": "TRAPPIST-1e", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Best habitable zone candidate"},
    {"name": "TRAPPIST-1f", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Outer habitable zone"},
    {"name": "TRAPPIST-1g", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Outer habitable zone"},
    {"name": "TRAPPIST-1h", "host": "TRAPPIST-1",
     "ra": 346.6220, "dec": -5.0413,
     "distance_ly": 40.7, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Outermost planet"},
    # Proxima Centauri
    {"name": "Proxima Centauri b",
     "host": "Proxima Centauri",
     "ra": 217.4290, "dec": -62.6796,
     "distance_ly": 4.2, "type": "Terrestrial",
     "discovery_year": 2016, "method": "Radial Velocity",
     "notes": "Nearest known exoplanet"},
    {"name": "Proxima Centauri d",
     "host": "Proxima Centauri",
     "ra": 217.4290, "dec": -62.6796,
     "distance_ly": 4.2, "type": "Sub-Earth",
     "discovery_year": 2022, "method": "Radial Velocity",
     "notes": "Very close orbit"},
    # 51 Pegasi
    {"name": "51 Pegasi b", "host": "51 Pegasi",
     "ra": 344.3667, "dec": 20.7689,
     "distance_ly": 50.9, "type": "Hot Jupiter",
     "discovery_year": 1995, "method": "Radial Velocity",
     "notes": "First exoplanet around sun-like star"},
    # Kepler systems
    {"name": "Kepler-186f", "host": "Kepler-186",
     "ra": 292.1671, "dec": 43.9572,
     "distance_ly": 582.0, "type": "Terrestrial",
     "discovery_year": 2014, "method": "Transit",
     "notes": "First Earth-sized habitable zone planet"},
    {"name": "Kepler-452b", "host": "Kepler-452",
     "ra": 292.1671, "dec": 44.3195,
     "distance_ly": 1400.0, "type": "Super-Earth",
     "discovery_year": 2015, "method": "Transit",
     "notes": "Earth cousin — similar size and orbit"},
    {"name": "Kepler-22b", "host": "Kepler-22",
     "ra": 286.6217, "dec": 47.8853,
     "distance_ly": 620.0, "type": "Super-Earth",
     "discovery_year": 2011, "method": "Transit",
     "notes": "First confirmed habitable zone planet"},
    {"name": "Kepler-69c", "host": "Kepler-69",
     "ra": 291.4863, "dec": 44.8498,
     "distance_ly": 2700.0, "type": "Super-Venus",
     "discovery_year": 2013, "method": "Transit",
     "notes": "Habitable zone super-Earth"},
    {"name": "Kepler-62e", "host": "Kepler-62",
     "ra": 284.7333, "dec": 45.3464,
     "distance_ly": 1200.0, "type": "Super-Earth",
     "discovery_year": 2013, "method": "Transit",
     "notes": "Water world candidate"},
    {"name": "Kepler-62f", "host": "Kepler-62",
     "ra": 284.7333, "dec": 45.3464,
     "distance_ly": 1200.0, "type": "Super-Earth",
     "discovery_year": 2013, "method": "Transit",
     "notes": "Outer habitable zone"},
    {"name": "Kepler-442b", "host": "Kepler-442",
     "ra": 281.4125, "dec": 39.2833,
     "distance_ly": 1206.0, "type": "Super-Earth",
     "discovery_year": 2015, "method": "Transit",
     "notes": "High Earth Similarity Index"},
    {"name": "Kepler-438b", "host": "Kepler-438",
     "ra": 281.0833, "dec": 41.9619,
     "distance_ly": 473.0, "type": "Terrestrial",
     "discovery_year": 2015, "method": "Transit",
     "notes": "Most Earth-like Kepler planet"},
    {"name": "Kepler-296e", "host": "Kepler-296",
     "ra": 285.7292, "dec": 46.9883,
     "distance_ly": 1670.0, "type": "Super-Earth",
     "discovery_year": 2014, "method": "Transit",
     "notes": "Habitable zone"},
    {"name": "Kepler-1649c", "host": "Kepler-1649",
     "ra": 290.5417, "dec": 41.0833,
     "distance_ly": 301.0, "type": "Terrestrial",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Almost Earth twin"},
    # HD systems
    {"name": "HD 209458 b", "host": "HD 209458",
     "ra": 330.7954, "dec": 18.8843,
     "distance_ly": 159.0, "type": "Hot Jupiter",
     "discovery_year": 1999, "method": "Transit",
     "notes": "First transiting exoplanet detected"},
    {"name": "HD 189733 b", "host": "HD 189733",
     "ra": 300.1792, "dec": 22.7108,
     "distance_ly": 63.0, "type": "Hot Jupiter",
     "discovery_year": 2005, "method": "Transit",
     "notes": "Blue planet — silicate rain"},
    {"name": "HD 40307 g", "host": "HD 40307",
     "ra": 89.8333, "dec": -60.0108,
     "distance_ly": 42.0, "type": "Super-Earth",
     "discovery_year": 2012, "method": "Radial Velocity",
     "notes": "Habitable zone super-Earth"},
    {"name": "HD 85512 b", "host": "HD 85512",
     "ra": 147.7458, "dec": -43.5786,
     "distance_ly": 36.0, "type": "Super-Earth",
     "discovery_year": 2011, "method": "Radial Velocity",
     "notes": "Habitable zone candidate"},
    # GJ (Gliese) systems
    {"name": "GJ 667C c", "host": "GJ 667C",
     "ra": 259.6292, "dec": -34.9972,
     "distance_ly": 23.6, "type": "Super-Earth",
     "discovery_year": 2011, "method": "Radial Velocity",
     "notes": "Habitable zone around M-dwarf"},
    {"name": "GJ 1214 b", "host": "GJ 1214",
     "ra": 258.8292, "dec": 4.9611,
     "distance_ly": 42.0, "type": "Water World",
     "discovery_year": 2009, "method": "Transit",
     "notes": "Super-Earth with thick atmosphere"},
    {"name": "GJ 876 b", "host": "GJ 876",
     "ra": 343.3208, "dec": -14.2572,
     "distance_ly": 15.3, "type": "Gas Giant",
     "discovery_year": 1998, "method": "Radial Velocity",
     "notes": "Nearest gas giant exoplanet"},
    {"name": "GJ 436 b", "host": "GJ 436",
     "ra": 175.5458, "dec": 26.7064,
     "distance_ly": 33.1, "type": "Neptune-like",
     "discovery_year": 2004, "method": "Radial Velocity",
     "notes": "Hot ice Neptune"},
    {"name": "GJ 504 b", "host": "GJ 504",
     "ra": 206.8833, "dec": 9.9986,
     "distance_ly": 57.3, "type": "Gas Giant",
     "discovery_year": 2013, "method": "Direct Imaging",
     "notes": "Pink directly imaged planet"},
    # HR systems
    {"name": "HR 8799 b", "host": "HR 8799",
     "ra": 346.8696, "dec": 21.1344,
     "distance_ly": 129.0, "type": "Gas Giant",
     "discovery_year": 2008, "method": "Direct Imaging",
     "notes": "First multi-planet direct image"},
    {"name": "HR 8799 c", "host": "HR 8799",
     "ra": 346.8696, "dec": 21.1344,
     "distance_ly": 129.0, "type": "Gas Giant",
     "discovery_year": 2008, "method": "Direct Imaging",
     "notes": "Directly imaged"},
    {"name": "HR 8799 d", "host": "HR 8799",
     "ra": 346.8696, "dec": 21.1344,
     "distance_ly": 129.0, "type": "Gas Giant",
     "discovery_year": 2008, "method": "Direct Imaging",
     "notes": "Directly imaged"},
    {"name": "HR 8799 e", "host": "HR 8799",
     "ra": 346.8696, "dec": 21.1344,
     "distance_ly": 129.0, "type": "Gas Giant",
     "discovery_year": 2010, "method": "Direct Imaging",
     "notes": "Innermost directly imaged"},
    # TOI systems
    {"name": "TOI-700 d", "host": "TOI-700",
     "ra": 93.6875, "dec": -65.5778,
     "distance_ly": 101.4, "type": "Terrestrial",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Earth-sized in habitable zone"},
    {"name": "TOI-700 e", "host": "TOI-700",
     "ra": 93.6875, "dec": -65.5778,
     "distance_ly": 101.4, "type": "Terrestrial",
     "discovery_year": 2023, "method": "Transit",
     "notes": "Second habitable zone planet"},
    {"name": "TOI-1452 b", "host": "TOI-1452",
     "ra": 313.2833, "dec": 68.5333,
     "distance_ly": 100.0, "type": "Super-Earth",
     "discovery_year": 2022, "method": "Transit",
     "notes": "Potential ocean world"},
    {"name": "TOI-715 b", "host": "TOI-715",
     "ra": 154.7708, "dec": -25.1611,
     "distance_ly": 137.0, "type": "Super-Earth",
     "discovery_year": 2024, "method": "Transit",
     "notes": "Habitable zone super-Earth"},
    # LHS systems
    {"name": "LHS 1140 b", "host": "LHS 1140",
     "ra": 17.9708, "dec": -15.2681,
     "distance_ly": 41.0, "type": "Super-Earth",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Potentially habitable rocky world"},
    {"name": "LHS 3844 b", "host": "LHS 3844",
     "ra": 332.7375, "dec": -44.3806,
     "distance_ly": 48.6, "type": "Terrestrial",
     "discovery_year": 2019, "method": "Transit",
     "notes": "Rocky with bare surface"},
    # Other notable systems
    {"name": "55 Cancri e", "host": "55 Cancri",
     "ra": 133.1492, "dec": 28.3300,
     "distance_ly": 41.0, "type": "Super-Earth",
     "discovery_year": 2004, "method": "Radial Velocity",
     "notes": "Lava world — year is 18 hours"},
    {"name": "Tau Ceti e", "host": "Tau Ceti",
     "ra": 26.0167, "dec": -15.9375,
     "distance_ly": 11.9, "type": "Super-Earth",
     "discovery_year": 2012, "method": "Radial Velocity",
     "notes": "Nearest potentially habitable planet"},
    {"name": "Tau Ceti f", "host": "Tau Ceti",
     "ra": 26.0167, "dec": -15.9375,
     "distance_ly": 11.9, "type": "Super-Earth",
     "discovery_year": 2012, "method": "Radial Velocity",
     "notes": "Habitable zone candidate"},
    {"name": "Wolf 1061 c", "host": "Wolf 1061",
     "ra": 248.0208, "dec": -12.5236,
     "distance_ly": 13.8, "type": "Super-Earth",
     "discovery_year": 2015, "method": "Radial Velocity",
     "notes": "Nearest habitable zone planet"},
    {"name": "Gliese 832 c", "host": "Gliese 832",
     "ra": 323.3625, "dec": -49.0097,
     "distance_ly": 16.1, "type": "Super-Earth",
     "discovery_year": 2014, "method": "Radial Velocity",
     "notes": "Nearest potentially habitable"},
    {"name": "K2-18 b", "host": "K2-18",
     "ra": 172.5625, "dec": 7.5883,
     "distance_ly": 124.0, "type": "Sub-Neptune",
     "discovery_year": 2015, "method": "Transit",
     "notes": "Possible water ocean world — JWST target"},
    {"name": "WASP-121 b", "host": "WASP-121",
     "ra": 107.5958, "dec": -39.0942,
     "distance_ly": 850.0, "type": "Ultra-Hot Jupiter",
     "discovery_year": 2015, "method": "Transit",
     "notes": "Stratosphere with water vapour"},
    {"name": "WASP-17 b", "host": "WASP-17",
     "ra": 239.1833, "dec": -28.0681,
     "distance_ly": 1000.0, "type": "Hot Jupiter",
     "discovery_year": 2009, "method": "Transit",
     "notes": "First retrograde orbit planet"},
    {"name": "WASP-76 b", "host": "WASP-76",
     "ra": 28.7750, "dec": 2.0917,
     "distance_ly": 634.0, "type": "Ultra-Hot Jupiter",
     "discovery_year": 2013, "method": "Transit",
     "notes": "Iron rain on night side"},
    {"name": "WASP-39 b", "host": "WASP-39",
     "ra": 159.4083, "dec": -3.4444,
     "distance_ly": 700.0, "type": "Hot Saturn",
     "discovery_year": 2011, "method": "Transit",
     "notes": "First CO2 detected by JWST"},
    {"name": "Beta Pictoris b",
     "host": "Beta Pictoris",
     "ra": 86.8213, "dec": -51.0664,
     "distance_ly": 63.4, "type": "Gas Giant",
     "discovery_year": 2008, "method": "Direct Imaging",
     "notes": "Directly imaged in debris disk"},
    {"name": "Fomalhaut b", "host": "Fomalhaut",
     "ra": 344.4129, "dec": -29.6223,
     "distance_ly": 25.0, "type": "Unknown",
     "discovery_year": 2008, "method": "Direct Imaging",
     "notes": "First optically imaged exoplanet"},
    {"name": "HIP 65426 b", "host": "HIP 65426",
     "ra": 201.0250, "dec": -51.9978,
     "distance_ly": 385.0, "type": "Gas Giant",
     "discovery_year": 2017, "method": "Direct Imaging",
     "notes": "First JWST directly imaged exoplanet"},
    {"name": "AF Leporis b", "host": "AF Leporis",
     "ra": 84.3542, "dec": -21.6144,
     "distance_ly": 87.5, "type": "Gas Giant",
     "discovery_year": 2023, "method": "Direct Imaging",
     "notes": "Youngest directly imaged planet"},
    {"name": "Pi Mensae c", "host": "Pi Mensae",
     "ra": 84.2917, "dec": -80.4694,
     "distance_ly": 59.5, "type": "Super-Earth",
     "discovery_year": 2018, "method": "Transit",
     "notes": "TESS first planet detection"},
    {"name": "L 98-59 b", "host": "L 98-59",
     "ra": 124.5292, "dec": -68.3181,
     "distance_ly": 34.6, "type": "Terrestrial",
     "discovery_year": 2019, "method": "Transit",
     "notes": "Smallest TESS planet"},
    {"name": "LP 890-9 c", "host": "LP 890-9",
     "ra": 22.7042, "dec": -34.5069,
     "distance_ly": 98.6, "type": "Super-Earth",
     "discovery_year": 2022, "method": "Transit",
     "notes": "Second most Earth-like planet found"},
    {"name": "Ross 128 b", "host": "Ross 128",
     "ra": 176.9375, "dec": 0.8003,
     "distance_ly": 11.0, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Radial Velocity",
     "notes": "Second nearest temperate exoplanet"},
    {"name": "Teegarden b", "host": "Teegarden Star",
     "ra": 53.0792, "dec": 16.8831,
     "distance_ly": 12.5, "type": "Terrestrial",
     "discovery_year": 2019, "method": "Radial Velocity",
     "notes": "High Earth Similarity Index"},
    {"name": "Teegarden c", "host": "Teegarden Star",
     "ra": 53.0792, "dec": 16.8831,
     "distance_ly": 12.5, "type": "Terrestrial",
     "discovery_year": 2019, "method": "Radial Velocity",
     "notes": "Second planet in system"},
    {"name": "YZ Ceti b", "host": "YZ Ceti",
     "ra": 16.3417, "dec": -16.6497,
     "distance_ly": 12.1, "type": "Terrestrial",
     "discovery_year": 2017, "method": "Radial Velocity",
     "notes": "Potentially radio-detectable"},
    {"name": "Barnard b", "host": "Barnard Star",
     "ra": 269.4521, "dec": 4.6933,
     "distance_ly": 5.96, "type": "Super-Earth",
     "discovery_year": 2024, "method": "Radial Velocity",
     "notes": "Second nearest star system"},
    {"name": "epsilon Eridani b",
     "host": "Epsilon Eridani",
     "ra": 53.2329, "dec": -9.4583,
     "distance_ly": 10.5, "type": "Gas Giant",
     "discovery_year": 2000, "method": "Radial Velocity",
     "notes": "Nearest confirmed giant exoplanet"},
    {"name": "Upsilon Andromedae d",
     "host": "Upsilon Andromedae",
     "ra": 24.1988, "dec": 41.4056,
     "distance_ly": 44.0, "type": "Gas Giant",
     "discovery_year": 1999, "method": "Radial Velocity",
     "notes": "First multi-planet system found"},
    {"name": "PSR 1257+12 b",
     "host": "PSR 1257+12",
     "ra": 194.9583, "dec": 12.6833,
     "distance_ly": 2300.0, "type": "Pulsar Planet",
     "discovery_year": 1992, "method": "Pulsar Timing",
     "notes": "Very first exoplanet discovered"},
    {"name": "HAT-P-7 b", "host": "HAT-P-7",
     "ra": 292.2500, "dec": 47.9681,
     "distance_ly": 1040.0, "type": "Hot Jupiter",
     "discovery_year": 2008, "method": "Transit",
     "notes": "Ruby rain on night side"},
    {"name": "KELT-9 b", "host": "KELT-9",
     "ra": 290.4167, "dec": 39.8583,
     "distance_ly": 670.0, "type": "Ultra-Hot Jupiter",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Hottest known exoplanet — 4300°C"},
    {"name": "TrES-2 b", "host": "TrES-2",
     "ra": 286.8917, "dec": 49.3167,
     "distance_ly": 750.0, "type": "Hot Jupiter",
     "discovery_year": 2006, "method": "Transit",
     "notes": "Darkest known exoplanet"},
    {"name": "Kepler-16 b", "host": "Kepler-16",
     "ra": 287.8083, "dec": 51.7578,
     "distance_ly": 200.0, "type": "Gas Giant",
     "discovery_year": 2011, "method": "Transit",
     "notes": "Real Tatooine — orbits two stars"},
    {"name": "PH1 b", "host": "PH1",
     "ra": 290.4125, "dec": 40.9800,
     "distance_ly": 5000.0, "type": "Gas Giant",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Planet with four suns"},
    {"name": "Kepler-47 b", "host": "Kepler-47",
     "ra": 291.4917, "dec": 46.9183,
     "distance_ly": 4900.0, "type": "Sub-Neptune",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Circumbinary planet"},
    {"name": "Kepler-47 c", "host": "Kepler-47",
     "ra": 291.4917, "dec": 46.9183,
     "distance_ly": 4900.0, "type": "Gas Giant",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Habitable zone circumbinary"},
    {"name": "55 Cancri f", "host": "55 Cancri",
     "ra": 133.1492, "dec": 28.3300,
     "distance_ly": 41.0, "type": "Saturn-like",
     "discovery_year": 2005, "method": "Radial Velocity",
     "notes": "Part of 5-planet system"},
    {"name": "Gliese 581 g", "host": "Gliese 581",
     "ra": 229.8625, "dec": -7.7172,
     "distance_ly": 20.3, "type": "Super-Earth",
     "discovery_year": 2010, "method": "Radial Velocity",
     "notes": "Controversial habitable zone planet"},
    {"name": "HD 10180 g", "host": "HD 10180",
     "ra": 23.9667, "dec": -60.5028,
     "distance_ly": 127.0, "type": "Neptune-like",
     "discovery_year": 2010, "method": "Radial Velocity",
     "notes": "7-planet system"},
    {"name": "Kepler-90 i", "host": "Kepler-90",
     "ra": 293.4042, "dec": 49.2294,
     "distance_ly": 2545.0, "type": "Super-Earth",
     "discovery_year": 2017, "method": "Transit",
     "notes": "AI-discovered 8th planet"},
    {"name": "Kepler-11 f", "host": "Kepler-11",
     "ra": 291.4042, "dec": 41.9236,
     "distance_ly": 2000.0, "type": "Sub-Neptune",
     "discovery_year": 2011, "method": "Transit",
     "notes": "Flat 6-planet system"},
    {"name": "Kepler-36 b", "host": "Kepler-36",
     "ra": 290.9333, "dec": 49.9733,
     "distance_ly": 1500.0, "type": "Super-Earth",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Two very different planets close together"},
    {"name": "HD 219134 b", "host": "HD 219134",
     "ra": 348.3292, "dec": 57.1706,
     "distance_ly": 21.3, "type": "Super-Earth",
     "discovery_year": 2015, "method": "Radial Velocity",
     "notes": "Nearest confirmed rocky exoplanet"},
    {"name": "55 Cancri d", "host": "55 Cancri",
     "ra": 133.1492, "dec": 28.3300,
     "distance_ly": 41.0, "type": "Gas Giant",
     "discovery_year": 2002, "method": "Radial Velocity",
     "notes": "Jupiter analogue"},
    {"name": "HD 95086 b", "host": "HD 95086",
     "ra": 164.2500, "dec": -68.0258,
     "distance_ly": 295.0, "type": "Gas Giant",
     "discovery_year": 2013, "method": "Direct Imaging",
     "notes": "Directly imaged in debris disk"},
    {"name": "2M1207 b", "host": "2M1207",
     "ra": 181.8583, "dec": -39.8467,
     "distance_ly": 170.0, "type": "Gas Giant",
     "discovery_year": 2004, "method": "Direct Imaging",
     "notes": "First directly imaged exoplanet"},
    {"name": "ROXs 42Bb", "host": "ROXs 42B",
     "ra": 246.4667, "dec": -24.3917,
     "distance_ly": 460.0, "type": "Gas Giant",
     "discovery_year": 2013, "method": "Direct Imaging",
     "notes": "Young directly imaged planet"},
    {"name": "51 Eridani b", "host": "51 Eridani",
     "ra": 76.3917, "dec": -2.4736,
     "distance_ly": 96.0, "type": "Gas Giant",
     "discovery_year": 2015, "method": "Direct Imaging",
     "notes": "Youngest Jupiter-like directly imaged"},
    {"name": "COCONUTS-2 b", "host": "COCONUTS-2",
     "ra": 116.3083, "dec": -21.9694,
     "distance_ly": 35.0, "type": "Gas Giant",
     "discovery_year": 2021, "method": "Direct Imaging",
     "notes": "Widest known planetary orbit"},
    {"name": "WD 1856 b", "host": "WD 1856+534",
     "ra": 284.4417, "dec": 53.5083,
     "distance_ly": 80.0, "type": "Gas Giant",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Planet orbiting a white dwarf"},
    {"name": "K2-141 b", "host": "K2-141",
     "ra": 87.2208, "dec": 17.4125,
     "distance_ly": 202.0, "type": "Super-Earth",
     "discovery_year": 2018, "method": "Transit",
     "notes": "Lava ocean world"},
    {"name": "GJ 3470 b", "host": "GJ 3470",
     "ra": 124.6875, "dec": 15.3711,
     "distance_ly": 96.7, "type": "Neptune-like",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Losing atmosphere rapidly"},
    {"name": "WASP-107 b", "host": "WASP-107",
     "ra": 184.2792, "dec": -10.1500,
     "distance_ly": 212.0, "type": "Gas Giant",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Cotton candy density — JWST target"},
    {"name": "XO-1 b", "host": "XO-1",
     "ra": 240.5458, "dec": 28.1706,
     "distance_ly": 200.0, "type": "Hot Jupiter",
     "discovery_year": 2006, "method": "Transit",
     "notes": "Amateur astronomers contributed"},
    {"name": "Qatar-1 b", "host": "Qatar-1",
     "ra": 312.1833, "dec": 65.1597,
     "distance_ly": 550.0, "type": "Hot Jupiter",
     "discovery_year": 2010, "method": "Transit",
     "notes": "First planet from Qatar survey"},
    {"name": "MASCARA-1 b", "host": "MASCARA-1",
     "ra": 271.8292, "dec": 14.8419,
     "distance_ly": 880.0, "type": "Hot Jupiter",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Bright host star"},
    {"name": "NGTS-1 b", "host": "NGTS-1",
     "ra": 91.0833, "dec": -34.0833,
     "distance_ly": 600.0, "type": "Hot Jupiter",
     "discovery_year": 2017, "method": "Transit",
     "notes": "Monster planet orbiting small star"},
    {"name": "AU Microscopii b",
     "host": "AU Microscopii",
     "ra": 311.2917, "dec": -31.3408,
     "distance_ly": 31.9, "type": "Neptune-like",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Very young system — 22 million years"},
    {"name": "DS Tucanae A b",
     "host": "DS Tucanae A",
     "ra": 7.6208, "dec": -69.1958,
     "distance_ly": 150.0, "type": "Sub-Neptune",
     "discovery_year": 2019, "method": "Transit",
     "notes": "Young planet losing atmosphere"},
    {"name": "V1298 Tau b", "host": "V1298 Tau",
     "ra": 63.8542, "dec": 20.1958,
     "distance_ly": 360.0, "type": "Sub-Saturn",
     "discovery_year": 2019, "method": "Transit",
     "notes": "23 million year old system"},
    {"name": "Kepler-51 b", "host": "Kepler-51",
     "ra": 297.6583, "dec": 49.7250,
     "distance_ly": 2600.0, "type": "Super-puff",
     "discovery_year": 2012, "method": "Transit",
     "notes": "Cotton candy planet"},
    {"name": "HAT-P-11 b", "host": "HAT-P-11",
     "ra": 297.7083, "dec": 48.0806,
     "distance_ly": 123.0, "type": "Neptune-like",
     "discovery_year": 2009, "method": "Transit",
     "notes": "First Neptune with detected atmosphere"},
    {"name": "GK 3240 b", "host": "GJ 3240",
     "ra": 62.1042, "dec": 44.7042,
     "distance_ly": 160.0, "type": "Super-Earth",
     "discovery_year": 2020, "method": "Transit",
     "notes": "TESS detection"},
    {"name": "TOI-849 b", "host": "TOI-849",
     "ra": 106.0083, "dec": -39.8625,
     "distance_ly": 730.0, "type": "Neptune Desert",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Exposed planetary core"},
    {"name": "LTT 9779 b", "host": "LTT 9779",
     "ra": 337.9833, "dec": -28.4153,
     "distance_ly": 264.0, "type": "Ultra-hot Neptune",
     "discovery_year": 2020, "method": "Transit",
     "notes": "Mirror-like metal clouds"},
    {"name": "Kepler-7 b", "host": "Kepler-7",
     "ra": 291.4208, "dec": 41.0511,
     "distance_ly": 3000.0, "type": "Hot Jupiter",
     "discovery_year": 2010, "method": "Transit",
     "notes": "First cloud map of an exoplanet"},
    {"name": "WASP-43 b", "host": "WASP-43",
     "ra": 107.4167, "dec": -9.8031,
     "distance_ly": 261.0, "type": "Hot Jupiter",
     "discovery_year": 2011, "method": "Transit",
     "notes": "Full atmosphere map by Hubble"},
    {"name": "HD 149026 b", "host": "HD 149026",
     "ra": 248.5208, "dec": 38.3486,
     "distance_ly": 257.0, "type": "Saturn-like",
     "discovery_year": 2005, "method": "Transit",
     "notes": "Dense core — 70 Earth masses"},
    {"name": "COROT-7 b", "host": "COROT-7",
     "ra": 100.7333, "dec": -1.0369,
     "distance_ly": 489.0, "type": "Super-Earth",
     "discovery_year": 2009, "method": "Transit",
     "notes": "First confirmed rocky exoplanet"},
    {"name": "Kepler-78 b", "host": "Kepler-78",
     "ra": 285.8000, "dec": 44.3042,
     "distance_ly": 400.0, "type": "Terrestrial",
     "discovery_year": 2013, "method": "Transit",
     "notes": "Earth twin in size and density"},
    {"name": "55 Cancri b", "host": "55 Cancri",
     "ra": 133.1492, "dec": 28.3300,
     "distance_ly": 41.0, "type": "Gas Giant",
     "discovery_year": 1996, "method": "Radial Velocity",
     "notes": "First of 5-planet system"},
    {"name": "HD 128311 b", "host": "HD 128311",
     "ra": 218.8708, "dec": 9.7792,
     "distance_ly": 54.0, "type": "Gas Giant",
     "discovery_year": 2002, "method": "Radial Velocity",
     "notes": "Resonant orbit system"},
    {"name": "nu2 Lupi b", "host": "nu2 Lupi",
     "ra": 237.1083, "dec": -48.3181,
     "distance_ly": 48.0, "type": "Super-Earth",
     "discovery_year": 2019, "method": "Transit",
     "notes": "CHEOPS characterised system"},
    {"name": "pi Mensae b", "host": "pi Mensae",
     "ra": 84.2917, "dec": -80.4694,
     "distance_ly": 59.5, "type": "Gas Giant",
     "discovery_year": 2001, "method": "Radial Velocity",
     "notes": "Eccentric giant companion"},
]

def get_exoplanet_objects():
    """
    Return exoplanets in the same format as OBJECTS
    in object_visibility.py for compatibility.
    """
    objects = {}
    for planet in FAMOUS_EXOPLANETS:
        key = f"{planet['name']} (Exoplanet)"
        objects[key] = {
            "type":   "exoplanet",
            "ra":     planet["ra"],
            "dec":    planet["dec"],
            "host":   planet["host"],
            "distance_ly":    planet["distance_ly"],
            "planet_type":    planet["type"],
            "discovery_year": planet["discovery_year"],
            "method":         planet["method"],
            "notes":          planet["notes"]
        }
    return objects

def get_exoplanet_info(name):
    """Get full info for a specific exoplanet."""
    for planet in FAMOUS_EXOPLANETS:
        if planet["name"] in name:
            return planet
    return None

def get_host_star_visibility(ra_deg, dec_deg,
                              lat, lon):
    """
    Calculate if the host star is visible from
    an observatory right now.
    Uses RA/Dec to get altitude/azimuth.
    """
    import ephem
    import math

    obs          = ephem.Observer()
    obs.lat      = str(lat)
    obs.long     = str(lon)
    obs.date     = ephem.now()
    obs.pressure = 0

    # Create a fixed body at the given coordinates
    star      = ephem.FixedBody()
    star._ra  = ephem.degrees(str(ra_deg))
    star._dec = ephem.degrees(str(dec_deg))
    star.compute(obs)

    alt = math.degrees(float(star.alt))
    az  = math.degrees(float(star.az))

    return {
        "altitude": round(alt, 1),
        "azimuth":  round(az, 1),
        "visible":  alt >= 10
    }


if __name__ == "__main__":
    print(f"\n  Exoplanet catalogue: "
          f"{len(FAMOUS_EXOPLANETS)} planets\n")

    types = {}
    for p in FAMOUS_EXOPLANETS:
        t = p["type"]
        types[t] = types.get(t, 0) + 1

    print("  Types:")
    for t, count in sorted(
        types.items(), key=lambda x: -x[1]
    ):
        print(f"    {t:<20} — {count}")

    methods = {}
    for p in FAMOUS_EXOPLANETS:
        m = p["method"]
        methods[m] = methods.get(m, 0) + 1

    print("\n  Discovery methods:")
    for m, count in sorted(
        methods.items(), key=lambda x: -x[1]
    ):
        print(f"    {m:<20} — {count}")

    print(f"\n  Nearest: "
          f"{min(FAMOUS_EXOPLANETS, key=lambda x: x['distance_ly'])['name']} "
          f"({min(p['distance_ly'] for p in FAMOUS_EXOPLANETS)} ly)")
    print(f"  Most recent: "
          f"{max(FAMOUS_EXOPLANETS, key=lambda x: x['discovery_year'])['name']} "
          f"({max(p['discovery_year'] for p in FAMOUS_EXOPLANETS)})\n")